export enum RepoToken {
  DATA_SOURCE                  = "DATA_SOURCE",
  CONTACT_REPOSITORY           = "CONTACT_REPOSITORY",   
  CONTACT_SOURCE_REPOSITORY    = "CONTACT_SOURCE_REPOSITORY",   
  CONTACT_OUTBOX_REPOSITORY    = "CONTACT_OUTBOX_REPOSITORY",   
  CONTACT_ACCT_REL_REPOSITORY  = "CONTACT_ACCT_REL_REPOSITORY"   
}